name: ✨ Feature Request
description: Suggest an idea for this project
title: "[FEATURE] "
labels: enhancement

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the details below.

  - type: input
    id: summary
    attributes:
      label: Summary
      placeholder: A clear and concise description of what the feature should do.

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature needed? What problem does it solve?

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other solutions you tried or considered

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      placeholder: Add any other context or screenshots about the feature request here.
