#Requires -Version 5.1
<#
.SYNOPSIS
    Start the development environment.

.DESCRIPTION
    Starts local infrastructure (DB/Redis) and runs migrations, or pulls prebuilt images.

.PARAMETER Mode
    - local: Start local DB/Redis infra + run migrations (default)
    - prebuilt: Pull GHCR images via deploy/compose

.EXAMPLE
    .\scripts\dev-up.ps1
    .\scripts\dev-up.ps1 -Mode local
    .\scripts\dev-up.ps1 -Mode prebuilt
#>

param(
    [ValidateSet("local", "prebuilt")]
    [string]$Mode = "local",
    [switch]$Help
)

$ErrorActionPreference = "Stop"

function Show-Usage {
    Write-Host "Usage: dev-up.ps1 [-Mode local|prebuilt]"
    Write-Host ""
    Write-Host "  -Mode local     Start local DB/Redis infra + run migrations (default)"
    Write-Host "  -Mode prebuilt  Pull GHCR images via deploy/compose"
    Write-Host "  -Help           Show this help message"
}

if ($Help) {
    Show-Usage
    exit 0
}

# Resolve paths
$RootDir = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$EnvFile = Join-Path $RootDir "deploy\compose\.env"
$ComposeFile = Join-Path $RootDir "deploy\compose\docker-compose.yml"
$LocalComposeFile = Join-Path $RootDir "docker-compose.yml"

# Check for Docker (installed and running)
try {
    $null = docker version 2>&1
} catch {
    Write-Host "Docker is not installed or not in PATH." -ForegroundColor Red
    exit 1
}
if ($LASTEXITCODE -ne 0) {
    Write-Host "Docker is not running. Please start Docker Desktop and try again." -ForegroundColor Red
    exit 1
}

if ($Mode -eq "prebuilt") {
    # Prebuilt mode - same as prod-up
    if (-not (Test-Path $EnvFile)) {
        Write-Host "Missing $EnvFile." -ForegroundColor Red
        Write-Host "Copy deploy\compose\.env.example to deploy\compose\.env and edit it first."
        exit 1
    }

    Write-Host "Pulling prebuilt images (GHCR)..." -ForegroundColor Cyan
    docker compose --env-file $EnvFile -f $ComposeFile pull
    if ($LASTEXITCODE -ne 0) {
        Write-Host "Failed to pull images." -ForegroundColor Red
        exit 1
    }

    Write-Host "Starting prebuilt stack..." -ForegroundColor Cyan
    docker compose --env-file $EnvFile -f $ComposeFile up -d
    if ($LASTEXITCODE -ne 0) {
        Write-Host "Failed to start stack." -ForegroundColor Red
        exit 1
    }

    Write-Host "Done." -ForegroundColor Green
    exit 0
}

# Local mode - uses hardcoded credentials from docker-compose.yml
$FrontendDir = Join-Path $RootDir "frontend"
$EnvLocalFile = Join-Path $FrontendDir ".env.local"
$LocalDevDbUrl = "postgresql://financeuser:financepass@localhost:5433/finance_db"

# Create frontend/.env.local from deploy/compose/.env
Write-Host "Creating frontend/.env.local..." -ForegroundColor Cyan
$envLocalContent = @()
$envLocalContent += "# Auto-generated by dev-up script for local development"
$envLocalContent += "# Do not commit this file"
$envLocalContent += ""
$envLocalContent += "# Local dev database (matches docker-compose.yml)"
$envLocalContent += "DATABASE_URL=$LocalDevDbUrl"
$envLocalContent += ""
$envLocalContent += "# Local dev auth URL"
$envLocalContent += "BETTER_AUTH_URL=http://localhost:3000"

# Copy relevant variables from deploy/compose/.env if it exists
if (Test-Path $EnvFile) {
    $composeEnv = Get-Content $EnvFile -ErrorAction SilentlyContinue
    $varsToInclude = @(
        "INTERNAL_AUTH_SECRET",
        "BETTER_AUTH_SECRET",
        "OPENAI_API_KEY",
        "LOGO_DEV_API_KEY"
    )

    $envLocalContent += ""
    $envLocalContent += "# Copied from deploy/compose/.env"

    foreach ($line in $composeEnv) {
        foreach ($varName in $varsToInclude) {
            if ($line -match "^$varName=(.*)$") {
                $envLocalContent += $line
                break
            }
        }
    }
}

# Write .env.local file
$envLocalContent | Out-File -FilePath $EnvLocalFile -Encoding utf8
Write-Host "Created $EnvLocalFile" -ForegroundColor Green

Write-Host "Starting local infrastructure containers..." -ForegroundColor Cyan
docker compose -f $LocalComposeFile up -d --build
if ($LASTEXITCODE -ne 0) {
    Write-Host "Failed to start local infrastructure." -ForegroundColor Red
    exit 1
}

# Check for pnpm
$pnpmPath = Get-Command pnpm -ErrorAction SilentlyContinue
if (-not $pnpmPath) {
    Write-Host "pnpm not found. Please install pnpm first: https://pnpm.io/installation" -ForegroundColor Red
    exit 1
}

# Always use the local dev DATABASE_URL (matches docker-compose.yml credentials)
$env:DATABASE_URL = $LocalDevDbUrl
Write-Host "Using DATABASE_URL: $env:DATABASE_URL" -ForegroundColor Gray

# Check if node_modules exists, if not run pnpm install
$NodeModulesDir = Join-Path $FrontendDir "node_modules"
if (-not (Test-Path $NodeModulesDir)) {
    Write-Host "Installing frontend dependencies..." -ForegroundColor Cyan
    Push-Location $FrontendDir
    try {
        pnpm install
        if ($LASTEXITCODE -ne 0) {
            Write-Host "Failed to install dependencies." -ForegroundColor Red
            exit 1
        }
    } finally {
        Pop-Location
    }
}

# Wait for PostgreSQL to be ready
Write-Host "Waiting for PostgreSQL to be ready..." -ForegroundColor Cyan
$maxAttempts = 30
$attempt = 0
do {
    $attempt++
    $result = docker exec finance_db pg_isready -U financeuser -d finance_db 2>&1
    if ($LASTEXITCODE -eq 0) {
        Write-Host "PostgreSQL is ready." -ForegroundColor Green
        break
    }
    if ($attempt -ge $maxAttempts) {
        Write-Host "PostgreSQL did not become ready in time." -ForegroundColor Red
        exit 1
    }
    Start-Sleep -Seconds 1
} while ($true)

Write-Host "Applying database migrations..." -ForegroundColor Cyan
Push-Location $FrontendDir
try {
    pnpm db:migrate
    if ($LASTEXITCODE -ne 0) {
        Write-Host "Failed to run migrations." -ForegroundColor Red
        exit 1
    }
} finally {
    Pop-Location
}

Write-Host ""
Write-Host "Done." -ForegroundColor Green
Write-Host ""
Write-Host "To start the development server:" -ForegroundColor Cyan
Write-Host "  cd frontend"
Write-Host "  pnpm dev"
Write-Host ""
Write-Host "Then open http://localhost:3000" -ForegroundColor Gray
