#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

MODE="local"

usage() {
  cat <<'EOF'
Usage: dev-up.sh [--local|--prebuilt]

  --local     Start local DB/Redis infra + run migrations (default).
  --prebuilt  Pull GHCR images via deploy/compose.
EOF
}

for arg in "$@"; do
  case "$arg" in
    --local)
      MODE="local"
      ;;
    --prebuilt)
      MODE="prebuilt"
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $arg"
      usage
      exit 1
      ;;
  esac
done

if [ "$MODE" = "prebuilt" ]; then
  ENV_FILE="$ROOT_DIR/deploy/compose/.env"
  if [ ! -f "$ENV_FILE" ]; then
    echo "Missing $ENV_FILE."
    echo "Copy deploy/compose/.env.example to deploy/compose/.env and edit it first."
    exit 1
  fi

  echo "Pulling prebuilt images (GHCR)..."
  docker compose --env-file "$ENV_FILE" -f "$ROOT_DIR/deploy/compose/docker-compose.yml" pull
  echo "Starting prebuilt stack..."
  docker compose --env-file "$ENV_FILE" -f "$ROOT_DIR/deploy/compose/docker-compose.yml" up -d
  echo "Done."
  exit 0
fi

# Local mode - uses hardcoded credentials from docker-compose.yml
FRONTEND_DIR="$ROOT_DIR/frontend"
ENV_LOCAL_FILE="$FRONTEND_DIR/.env.local"
ENV_COMPOSE_FILE="$ROOT_DIR/deploy/compose/.env"
LOCAL_DEV_DB_URL="postgresql://financeuser:financepass@localhost:5433/finance_db"

# Create frontend/.env.local from deploy/compose/.env
echo "Creating frontend/.env.local..."
cat > "$ENV_LOCAL_FILE" << EOF
# Auto-generated by dev-up script for local development
# Do not commit this file

# Local dev database (matches docker-compose.yml)
DATABASE_URL=$LOCAL_DEV_DB_URL

# Local dev auth URL
BETTER_AUTH_URL=http://localhost:3000
EOF

# Copy relevant variables from deploy/compose/.env if it exists
if [ -f "$ENV_COMPOSE_FILE" ]; then
  echo "" >> "$ENV_LOCAL_FILE"
  echo "# Copied from deploy/compose/.env" >> "$ENV_LOCAL_FILE"

  for var in INTERNAL_AUTH_SECRET BETTER_AUTH_SECRET OPENAI_API_KEY LOGO_DEV_API_KEY; do
    value=$(grep "^$var=" "$ENV_COMPOSE_FILE" | head -n1)
    if [ -n "$value" ]; then
      echo "$value" >> "$ENV_LOCAL_FILE"
    fi
  done
fi

echo "Created $ENV_LOCAL_FILE"

echo "Starting local infrastructure containers..."
docker compose -f "$ROOT_DIR/docker-compose.yml" up -d --build

if ! command -v pnpm >/dev/null 2>&1; then
  echo "pnpm not found. Please install pnpm first: https://pnpm.io/installation"
  exit 1
fi

# Always use the local dev DATABASE_URL (matches docker-compose.yml credentials)
export DATABASE_URL="$LOCAL_DEV_DB_URL"
echo "Using DATABASE_URL: $DATABASE_URL"

# Check if node_modules exists, if not run pnpm install
if [ ! -d "$FRONTEND_DIR/node_modules" ]; then
  echo "Installing frontend dependencies..."
  (cd "$FRONTEND_DIR" && pnpm install)
fi

# Wait for PostgreSQL to be ready
echo "Waiting for PostgreSQL to be ready..."
max_attempts=30
attempt=0
until docker exec finance_db pg_isready -U financeuser -d finance_db >/dev/null 2>&1; do
  attempt=$((attempt + 1))
  if [ $attempt -ge $max_attempts ]; then
    echo "PostgreSQL did not become ready in time."
    exit 1
  fi
  sleep 1
done
echo "PostgreSQL is ready."

echo "Applying database migrations..."
(cd "$FRONTEND_DIR" && pnpm db:migrate)

echo ""
echo "Done."
echo ""
echo "To start the development server:"
echo "  cd frontend"
echo "  pnpm dev"
echo ""
echo "Then open http://localhost:3000"
